#!/usr/bin/env python3
"""Generate idempotent survey_responses INSERTs from a Google-Form CSV export.

This is the generator behind the one-time Civics & Elections backfill (see
README-civics-survey-import.md). It maps a Google Form "Responses" CSV onto the
field-survey schema (migrations 00053 + 00061) so historical form submissions
land in survey_responses shaped exactly like organic anonymous public submits.

    python3 scripts/ops/import-google-form-survey-responses.py \
        --csv /path/to/responses.csv > /tmp/seed.sql
    # then apply via Supabase Studio -> SQL Editor for the target project
    # (prod = cdbgkgkjnomjnpicaxqe). Do NOT commit the CSV or the generated SQL.

PII WARNING: the input CSV and the emitted SQL contain respondents' names,
emails, and phone numbers. Both are intentionally kept OUT of version control —
the data belongs in the database only. This generator itself is PII-free.

The generated SQL is idempotent: each row is guarded on (field_survey_id,
created_at), which is unique per submission, so re-runs never duplicate.

CSV columns are matched by header substring (Google Form question text), so the
exact wording can drift without breaking the mapping. Expected columns:
  Timestamp | Consent | observation | experience | salience | prior attempts |
  follow-up consent | name | mentor interest | email | phone
"""
import argparse
import csv
import sys

DQ = "$tul$"  # dollar-quote tag; aborts if it appears in the data

# experience label (substring, case-insensitive) -> standpoint key (migration 00061)
STANDPOINT_RULES = [
    ("work in this field", "work_in_field"),
    ("personally affected", "affected"),
    ("research or study", "research"),
    ("pay close attention", "pay_attention"),
    ("tried to fix", "tried_to_fix"),
    ("other", "other"),
]


def norm_ap(s: str) -> str:
    return (s or "").replace("’", "'").replace("‘", "'")


def find_col(header, *needles):
    for i, h in enumerate(header):
        hl = norm_ap(h).lower()
        if all(n in hl for n in needles):
            return i
    return None


def map_standpoint(experience: str):
    e = norm_ap(experience).strip().lower()
    if not e:
        return []
    for needle, key in STANDPOINT_RULES:
        if needle in e:
            return [key]
    raise SystemExit(f"Unmapped experience value: {experience!r}")


def parse_ts(ts: str, offset: str) -> str:
    ts = ts.strip()
    date_part, time_part = ts.split(" ", 1)
    m, d, y = date_part.split("/")
    hh, mm, ss = time_part.split(":")
    return f"{int(y):04d}-{int(m):02d}-{int(d):02d} {int(hh):02d}:{int(mm):02d}:{int(ss):02d}{offset}"


def lit(val):
    if val is None:
        return "NULL"
    if DQ in val:
        raise SystemExit(f"Dollar-quote tag {DQ} appears in a value; choose another tag")
    return f"{DQ}{val}{DQ}"


def arr(items):
    if not items:
        return "'{}'"
    return "'{" + ",".join(f'"{x}"' for x in items) + "}'"


def clean(s):
    return (s or "").strip()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csv", required=True, help="Google Form Responses CSV export")
    ap.add_argument("--slug", default="civics", help="field_surveys.share_slug (default: civics)")
    ap.add_argument("--consent-version", default="civics-2026-07")
    ap.add_argument("--moderation-status", default="approved",
                    choices=["pending", "approved", "rejected"])
    ap.add_argument("--tz-offset", default="-04",
                    help="offset for the form's local time (default -04 = America/New_York EDT)")
    args = ap.parse_args()

    with open(args.csv, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    header, data = rows[0], rows[1:]

    c_ts = find_col(header, "timestamp")
    c_obs = find_col(header, "observing")
    c_exp = find_col(header, "experience")
    c_sal = find_col(header, "how much")
    c_prior = find_col(header, "address this before")
    c_follow = find_col(header, "follow up")
    c_name = find_col(header, "your name")
    c_mentor = find_col(header, "mentor")
    c_email = find_col(header, "email")
    c_phone = find_col(header, "phone")
    for label, idx in [("Timestamp", c_ts), ("observation", c_obs)]:
        if idx is None:
            raise SystemExit(f"Could not locate the {label} column in the CSV header")

    civ = f"(SELECT id FROM field_surveys WHERE share_slug = '{args.slug}')"
    out = sys.stdout
    out.write(f"-- Generated by import-google-form-survey-responses.py --slug {args.slug}\n")
    out.write("-- Idempotent (guarded on field_survey_id + created_at). Apply once to the\n")
    out.write("-- target Supabase project. Contains PII: do NOT commit this file.\n\n")

    for i, r in enumerate(data, start=1):
        obs = clean(r[c_obs])
        if not obs:
            raise SystemExit(f"row {i}: empty observation (survey_responses.observation)")
        sal = clean(r[c_sal]) if c_sal is not None else ""
        salience = sal if sal.isdigit() and 1 <= int(sal) <= 5 else None
        email = clean(r[c_email]) if c_email is not None else ""
        email = email.lower() if "@" in email else None  # drop non-emails (e.g. a stray name)
        standpoint = map_standpoint(r[c_exp]) if c_exp is not None else []
        contactable = "open to being contacted" in norm_ap(r[c_follow] if c_follow is not None else "").lower()
        mentor = clean(r[c_mentor] if c_mentor is not None else "").lower().startswith("yes")
        ts = parse_ts(r[c_ts], args.tz_offset)

        vals = ", ".join([
            civ, "NULL", lit(obs), arr(standpoint),
            salience if salience is not None else "NULL",
            lit(clean(r[c_prior]) or None) if c_prior is not None else "NULL",
            "true", f"'{args.consent_version}'",
            "true" if contactable else "false",
            lit(clean(r[c_name]) or None) if c_name is not None else "NULL",
            lit(email),
            lit(clean(r[c_phone]) or None) if c_phone is not None else "NULL",
            "true" if mentor else "false",
            "NULL", f"'{args.moderation_status}'", "1", "NULL",
            f"TIMESTAMPTZ '{ts}'",
        ])
        cols = ("field_survey_id, participant_id, observation, standpoint, salience, "
                "prior_attempts, consent_participation, consent_version, contactable, "
                "submitter_name, submitter_email, submitter_phone, mentor_interest, "
                "source_url, moderation_status, schema_version, ip_hash, created_at")
        out.write(f"INSERT INTO survey_responses ({cols})\n")
        out.write(f"SELECT {vals}\n")
        out.write("WHERE NOT EXISTS (\n")
        out.write("  SELECT 1 FROM survey_responses r\n")
        out.write(f"  WHERE r.field_survey_id = {civ}\n")
        out.write(f"    AND r.created_at = TIMESTAMPTZ '{ts}'\n")
        out.write(");\n\n")


if __name__ == "__main__":
    main()
