-- seed-sample-spotlights.sql
-- DEV / DEMO ONLY — NOT a migration; do NOT run against production.
-- Populates the public /stories page + landing spotlights row with the
-- onboarding-proto sample cohort (7 named spotlights) so the preview looks
-- lived-in. Production keeps the empty-until-real posture (migration 00036);
-- real spotlights arrive via the /admin/stories submission→publish flow.
-- Idempotent (ON CONFLICT (slug) DO NOTHING).

INSERT INTO spotlights (slug, name, role, tag, tag_label, quote, story, grad, status, sort_order, published_at)
VALUES
  ($tul$hector$tul$, $tul$Hector Perla$tul$, $tul$Inaugural AI Cohort$tul$, $tul$builder$tul$, $tul$Builder$tul$, $tul$The program gave me purpose again—connecting me with mission-driven public servants to tackle real problems. AI as an empowerment tool for people-first civic design.$tul$, $tul$["Hector came to the Labs mid-career, carrying an ADHD diagnosis he’d only recently named and a feeling that his systems-thinking never fit a job description. The Problem Sprint changed the frame: mapping benefits-navigation dead-ends in the Triangulator, his pattern-spotting was suddenly the team’s sharpest tool.","By Showcase his pod had shipped a plain-language eligibility guide piloted at three library branches. “I stopped apologizing for how my brain works,” he says. “The Labs gave it a job.”"]$tul$::jsonb, $tul$m-teal$tul$, $tul$published$tul$, 0, now()),
  ($tul$suzie$tul$, $tul$Suzie Zhang$tul$, $tul$Inaugural AI Cohort$tul$, $tul$career_changer$tul$, $tul$Career changer$tul$, $tul$I left realizing my gap is exactly where my strength lies—translating between tools, teams, and user needs. AI is about community, trust, and the human side of technology.$tul$, $tul$["Suzie spent eight years coaching financial literacy and assumed “learning AI” meant becoming an engineer. Her Practice Journal told a different story: week after week, the entries that mattered were about translation — turning what the tools could do into what her community could trust.","She now runs AI-literacy workshops for three community organizations, built on the playbook her project team returned to the commons."]$tul$::jsonb, $tul$m-forest$tul$, $tul$published$tul$, 1, now()),
  ($tul$jordan$tul$, $tul$Jordan Okafor$tul$, $tul$Civic & Elections Cycle$tul$, $tul$builder$tul$, $tul$Builder$tul$, $tul$Twelve resident interviews in, the problem stopped being abstract. We shipped a benefits guide three library branches actually use.$tul$, $tul$["Jordan joined the cycle to “learn AI tools” and got assigned twelve resident interviews instead. The evidence-first culture stuck: his solution proposal for BenefitsBot led the pod’s ballot, and the team formed around it within a week of the tally.","“Every other program hands you a curriculum. This one handed me a problem owner, a deadline, and people who’d actually use the thing.”"]$tul$::jsonb, $tul$m-navy$tul$, $tul$published$tul$, 2, now()),
  ($tul$elena$tul$, $tul$Elena Ruiz$tul$, $tul$Pod facilitator · Voting Access$tul$, $tul$mentor$tul$, $tul$Mentor$tul$, $tul$I came for the AI skills and stayed for the pod. Facilitating other people’s growth turned out to be the skill I was building all along.$tul$, $tul$["Elena registered as a volunteer, journaled her way through a cycle, and discovered the entries she reread were all about the pod — who was stuck, who was quiet, what unlocked them. When the Labs opened pod-facilitator roles (“Poderators”), her pod nominated her before she could ask.","She now facilitates Pod 2 · Voting Access, where the journal-health rhythm she once resisted is her favorite instrument."]$tul$::jsonb, $tul$m-teal$tul$, $tul$published$tul$, 3, now()),
  ($tul$marcus$tul$, $tul$Marcus Bell$tul$, $tul$Data Mentor · Two Cycles$tul$, $tul$mentor$tul$, $tul$Mentor$tul$, $tul$Mentoring here isn’t office hours into the void — teams bring evidence, and you get to challenge real thinking at the exact right moment.$tul$, $tul$["Marcus had mentored at three accelerators and burned out on all of them — “What should we do?” asked by teams who hadn’t tried anything. The Labs’ evidence-precedes-assistance rule flipped it: requests arrive with interview notes, failed experiments, and a specific place to push.","“The first request I got quoted their journal entries at me. I cleared my calendar.”"]$tul$::jsonb, $tul$m-forest$tul$, $tul$published$tul$, 4, now()),
  ($tul$aisha$tul$, $tul$Aisha Karim$tul$, $tul$Design Mentor$tul$, $tul$career_changer$tul$, $tul$Career changer$tul$, $tul$My case study became a playbook, the playbook became a workshop, and the workshop hired me. Build in the open — the commons pays you back.$tul$, $tul$["Aisha’s team published their case study under CC BY 4.0 like every Labs project. A civic-tech nonprofit found the playbook, ran the workshop, and then hired her to run it properly — her first design role after a decade in operations.","“A portfolio says ‘trust me.’ A public case study with peer sign-off says ‘check for yourself.’”"]$tul$::jsonb, $tul$m-navy$tul$, $tul$published$tul$, 5, now()),
  ($tul$rosa$tul$, $tul$Rosa Nguyen$tul$, $tul$Civic & Elections Cycle$tul$, $tul$builder$tul$, $tul$Builder$tul$, $tul$The kickoff assignment was two minutes of observations. Somehow that snowballed into the most useful thing I’ve ever built.$tul$, $tul$["Rosa’s first contribution was a field-survey entry about first-time voters — no account, two minutes, done. Those observations surfaced in her pod’s Triangulator session, became a problem statement, then a ballot-winning proposal she ended up registering for.","“I watched my own observation travel the whole pipeline. That’s when I understood what ‘build in the open’ actually means.”"]$tul$::jsonb, $tul$m-teal$tul$, $tul$published$tul$, 6, now())
ON CONFLICT (slug) DO NOTHING;
