-- Seed the public content tables from onboarding-proto's data.js files
-- (the prototype IS the CMS content, ported verbatim — voice rules apply:
-- edit copy in the prototype first, then re-seed). Idempotent via slug
-- ON CONFLICT upserts, so re-running refreshes content without duplicates.

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$anchor-01$q$, $q$kickoff-summit$q$, $q$Kickoff Summit — Civic & Elections Cycle$q$, $q$Summit$q$, $q$2026-07-14T18:00$q$, $q$2026-07-14T21:00$q$, $q$in_person$q$, $q$DC Public Library — Main branch$q$, NULL, $q$m-navy$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$Launch the cycle: meet the community, explore the theme, leave with one assignment — observe$q$, NULL, $q$["One night, one room, everyone who’s in. We open the Civic & Elections Cycle together: what the theme is, why it matters here, and how the next three months run.","You leave with one assignment — observe. Not solutions, not opinions. Things you’ve actually seen about how civic life works, or doesn’t. Those observations are the raw material the whole cycle builds on."]$q$::jsonb, $q$["m-navy","m-teal","m-forest"]$q$::jsonb, TRUE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$anchor-06$q$, $q$problem-sprint$q$, $q$Problem Sprint$q$, $q$Cycle event$q$, $q$2026-07-28T18:00$q$, $q$2026-07-28T20:30$q$, $q$in_person$q$, $q$Main branch$q$, NULL, $q$m-forest$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$Investigate together: pods work the field observations into problem situations — the material the whole cycle builds on$q$, NULL, $q$["This is where raw observations become real problems. Pods sit down with everything the community noticed and work it into problem situations — specific, grounded, worth three months of effort.","Come see how sensemaking works in the open. If you filled out the field survey, this is where your observations go to work."]$q$::jsonb, $q$["m-forest","m-teal","m-navy"]$q$::jsonb, TRUE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$anchor-02$q$, $q$meet-the-pods$q$, $q$Meet the Pods$q$, $q$Cycle event$q$, $q$2026-08-18T18:00$q$, $q$2026-08-18T20:30$q$, $q$in_person$q$, $q$Main branch$q$, NULL, $q$m-teal$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$Discovery goes public: pods present Problem Situations, stakeholder maps, and paradoxes. Bring your expertise and introductions$q$, NULL, $q$["Discovery goes public. Every pod presents what they found: the problem situation, the people inside it, and the paradox that makes it hard.","You don’t need to be in the cycle to matter here. Bring your expertise, your questions, and your introductions — a single \"you should talk to...\" can change a pod’s whole direction."]$q$::jsonb, $q$["m-teal","m-navy","m-forest"]$q$::jsonb, TRUE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$anchor-03$q$, $q$hackathon-frame-sprint$q$, $q$Hackathon — the Frame Sprint$q$, $q$Cycle event$q$, $q$2026-09-08T09:00$q$, $q$2026-09-08T18:00$q$, $q$in_person$q$, $q$Main branch$q$, NULL, $q$m-forest$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$Not primarily about coding: pods synthesize research into new frames, and projects emerge$q$, NULL, $q$["Not primarily about coding. A full day where pods take everything they’ve learned and reframe it — new ways of seeing the problem that make new solutions possible.","Projects are born here. By the end of the day, proposals exist, teams start forming, and the building phase has a shape."]$q$::jsonb, $q$["m-forest","m-navy","m-teal"]$q$::jsonb, TRUE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$anchor-04$q$, $q$meet-the-projects$q$, $q$Meet the Projects$q$, $q$Cycle event$q$, $q$2026-09-15T18:00$q$, $q$2026-09-15T20:30$q$, $q$in_person$q$, $q$Main branch$q$, NULL, $q$m-teal$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$Projects go public: the community critiques the framing before the prototype$q$, NULL, $q$["Projects go public before a single prototype exists — on purpose. The community critiques the framing while changing course is still cheap.","Come poke holes. The teams want it. A hard question tonight saves a month of building the wrong thing."]$q$::jsonb, $q$["m-teal","m-forest","m-navy"]$q$::jsonb, TRUE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$anchor-05$q$, $q$showcase-summit$q$, $q$Showcase Summit$q$, $q$Summit$q$, $q$2026-10-13T18:00$q$, $q$2026-10-13T21:00$q$, $q$in_person$q$, $q$DC Public Library — Main branch$q$, NULL, $q$m-navy$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$Prototypes, findings, failures, lessons — everything returns to the commons. Registration for the next cycle opens here$q$, NULL, $q$["The cycle ends the way it started: everyone in one room. Prototypes, findings, failures, lessons — all of it presented, all of it returned to the commons under open licenses.","Registration for the next cycle opens tonight. If you’ve been watching from the edge, this is the night to stop watching."]$q$::jsonb, $q$["m-navy","m-forest","m-teal"]$q$::jsonb, TRUE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-001$q$, $q$prompting-for-real-work$q$, $q$Prompting for real work$q$, NULL, $q$2026-07-09T18:00$q$, $q$2026-07-09T20:00$q$, $q$in_person$q$, $q$DC Public Library$q$, $q$assets/sample-workshop-recap.png$q$, NULL, $q$Free$q$, $q$Priya Shah · Product & AI mentor$q$, $q$A hands-on intro to prompting for everyday work$q$, $q$A laptop and a real task to try$q$, $q$["Two hours, one real task. You bring something from your actual week — an email backlog, a messy dataset, a report nobody reads — and leave with a working way to do it faster.","No theory without practice. No practice without your own work on the table. That’s the whole format."]$q$::jsonb, $q$["m-teal","m-forest","m-navy"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-002$q$, $q$design-for-non-designers$q$, $q$Design for non-designers$q$, NULL, $q$2026-07-16T18:00$q$, $q$2026-07-16T20:00$q$, $q$in_person$q$, $q$Tenley-Friendship$q$, NULL, $q$m-forest$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$Practical design fundamentals for builders$q$, $q$Something you'd like to make look better$q$, $q$["You don’t need to be a designer. You need about six rules and the discipline to use them. This session gives you both.","Bring something you’ve made that looks almost right. We’ll fix it together, and you’ll see exactly which rule was missing."]$q$::jsonb, $q$["m-forest","m-teal","m-navy"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-003$q$, $q$energy-climate-roundtable$q$, $q$Energy & Climate Roundtable$q$, NULL, $q$2026-07-22T19:00$q$, $q$2026-07-22T20:30$q$, $q$virtual$q$, $q$Online$q$, $q$assets/sample-square-event.png$q$, NULL, $q$Free$q$, $q$The Upskilling Labs$q$, $q$A community discussion on energy & climate work$q$, NULL, $q$["An open conversation about energy and climate work in our region — who’s doing it, what’s stuck, and where builders could actually help.","Roundtable means roundtable. Come ready to talk, not just listen. The link arrives after you save a spot."]$q$::jsonb, $q$["m-navy","m-teal","m-forest"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-004$q$, $q$ship-your-first-ai-tool$q$, $q$Ship your first AI tool$q$, NULL, $q$2026-07-29T18:00$q$, $q$2026-07-29T21:00$q$, $q$in_person$q$, $q$Main branch$q$, NULL, $q$m-teal$q$, $q$Free$q$, $q$Priya Shah · Product & AI mentor$q$, $q$Build and ship a small AI tool, start to finish$q$, $q$A laptop — no coding experience needed$q$, $q$["Three hours from blank page to shipped. Small on purpose: one input, one output, one thing it does well.","No coding experience needed — the tools have changed, and this session is the proof. You leave with a link you can send to someone."]$q$::jsonb, $q$["m-teal","m-navy","m-forest"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-005$q$, $q$build-night-ship-something-small$q$, $q$Build night: ship something small$q$, NULL, $q$2026-08-06T18:00$q$, $q$2026-08-06T21:00$q$, $q$in_person$q$, $q$Main branch$q$, NULL, $q$m-forest$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$An open work session to ship something small$q$, $q$Whatever you're working on$q$, $q$["No agenda, no speaker. A room full of people getting real work done, with help nearby when you’re stuck.","The only rule: pick something small enough to finish tonight. Shipping is a habit, and habits are built in reps."]$q$::jsonb, $q$["m-forest","m-navy","m-teal"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-006$q$, $q$data-storytelling$q$, $q$Data storytelling$q$, NULL, $q$2026-08-13T19:00$q$, $q$2026-08-13T20:30$q$, $q$virtual$q$, $q$Online$q$, NULL, $q$m-navy$q$, $q$Free$q$, $q$Marcus Bell · Data mentor$q$, $q$Turn data into a story people remember$q$, NULL, $q$["A chart nobody remembers is a chart that didn’t work. This session is about the difference between showing data and telling its story.","We’ll rebuild three real charts live — same numbers, completely different impact. You’ll never label an axis the same way again."]$q$::jsonb, $q$["m-navy","m-forest","m-teal"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-007$q$, $q$mentor-office-hours$q$, $q$Mentor office hours$q$, NULL, $q$2026-08-20T17:00$q$, $q$2026-08-20T19:00$q$, $q$in_person$q$, $q$DC Public Library$q$, NULL, $q$m-teal$q$, $q$Free$q$, $q$The Labs mentor bench$q$, $q$Drop in for 1:1 time with a mentor$q$, NULL, $q$["Twenty minutes, one mentor, your actual problem. Product, data, design, engineering, strategy — the bench covers it.","Come with the thing you’re avoiding. That’s always the right thing to bring."]$q$::jsonb, $q$["m-teal","m-forest","m-navy"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO events (api_id, slug, name, kind, start_at, end_at, location_type, location_name, img, grad, cost, host, description, bring, body, gallery, anchor)
VALUES ($q$evt-008$q$, $q$community-showcase-night$q$, $q$Community showcase night$q$, NULL, $q$2026-08-27T18:00$q$, $q$2026-08-27T20:30$q$, $q$in_person$q$, $q$Main branch$q$, NULL, $q$m-forest$q$, $q$Free$q$, $q$The Upskilling Labs$q$, $q$See what the community shipped this cycle$q$, NULL, $q$["Five-minute demos, real work, honest lessons. See what the community shipped — and what shipping actually took.","The fastest way to believe you could do this is watching someone like you do it. Come watch. Then come build."]$q$::jsonb, $q$["m-forest","m-teal","m-navy"]$q$::jsonb, FALSE)
ON CONFLICT (slug) DO UPDATE SET api_id=EXCLUDED.api_id, name=EXCLUDED.name, kind=EXCLUDED.kind, start_at=EXCLUDED.start_at, end_at=EXCLUDED.end_at, location_type=EXCLUDED.location_type, location_name=EXCLUDED.location_name, img=EXCLUDED.img, grad=EXCLUDED.grad, cost=EXCLUDED.cost, host=EXCLUDED.host, description=EXCLUDED.description, bring=EXCLUDED.bring, body=EXCLUDED.body, gallery=EXCLUDED.gallery, anchor=EXCLUDED.anchor, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$benefits-wayfinding-playbook$q$, $q$Benefits wayfinding playbook$q$, $q$playbook$q$, $q$Playbook · 18 pages$q$, NULL, $q$m-teal$q$, $q$How to run a plain-language benefits pilot at a library help desk — including what failed$q$, $q$["civic","playbook"]$q$::jsonb, $q$published$q$, $q$BenefitsBot · Spring 2026 Cycle$q$, $q$The BenefitsBot team$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["A pod spent a cycle at a library help desk watching people bounce off benefits paperwork. This playbook is everything they learned: the pilot design, the scripts, the signage, the failures.","Chapter six is the one to read first — “What didn’t work.” It’s the chapter most playbooks are too polite to write.","Fork it for your own help desk. That’s what the commons is for."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$first-time-voter-interview-kit$q$, $q$First-time voter interview kit$q$, $q$template$q$, $q$Template · CC BY 4.0$q$, NULL, $q$m-forest$q$, $q$The interview protocol and synthesis sheets a pod used with 40 first-time voters$q$, $q$["research","template"]$q$::jsonb, $q$published$q$, $q$Ballot Basics · Spring 2026 Cycle$q$, $q$The Ballot Basics team$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["Forty interviews with first-time voters, and the exact protocol that got them talking: the questions, the consent script, the synthesis sheets.","Nothing here is theoretical — every sheet has been used in the field. Copy the kit, swap the topic, and you have a working research protocol for your own project."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$prompting-fundamentals$q$, $q$Prompting fundamentals$q$, $q$guide$q$, $q$12 min read$q$, $q$assets/sample-alumni-spotlight.png$q$, NULL, $q$A written primer on prompting for everyday work$q$, $q$["ai","writing"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["The primer we wish someone had handed us: what a prompt actually is, why the same request fails one way and works another, and the five patterns that cover most everyday work.","Twelve minutes of reading, then it’s all practice. Pair it with the “Prompting for real work” session and bring your own task."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$ai-for-community-research$q$, $q$AI for community research$q$, $q$recording$q$, $q$38 min watch$q$, NULL, $q$m-teal$q$, $q$A recorded workshop on using AI in field research$q$, $q$["ai","research"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["A full workshop replay: using AI to process field notes, find patterns across interviews, and draft synthesis — without letting the tool flatten what people actually said.","The middle twenty minutes are a live demo on real (consented) field notes from a cycle pod. Watch that part twice."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$project-scoping-template$q$, $q$Project scoping template$q$, $q$template$q$, $q$Notion + PDF$q$, NULL, $q$m-forest$q$, $q$The scoping doc every pod starts from$q$, $q$["product"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["The one-page scoping doc every pod starts from: the problem, the smallest useful version, what you’ll measure, and what you’re explicitly not doing.","The “not doing” section is the whole trick. Scope grows back overnight — this page is how you cut it again in the morning."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$design-crit-basics$q$, $q$Design crit basics$q$, $q$recording$q$, $q$24 min watch$q$, NULL, $q$m-navy$q$, $q$How to give and take feedback that improves the work$q$, $q$["design"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["Feedback that improves the work is a skill, not a personality trait. This short session covers the crit format we use in every pod: describe, question, suggest — in that order.","Twenty-four minutes now saves your team a hundred defensive conversations later."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$data-cleaning-quickstart$q$, $q$Data cleaning quickstart$q$, $q$guide$q$, $q$9 min read$q$, NULL, $q$m-teal$q$, $q$From messy CSV to something you can trust$q$, $q$["data"]$q$::jsonb, $q$published$q$, NULL, $q$Marcus Bell · Data mentor$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["Every real dataset is messy. This quickstart is the checklist for the first hour: duplicates, empty cells, impossible values, and the columns that lie.","Nine minutes of reading, one rule to keep: never clean the original. Copy first, always."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$facilitation-playbook$q$, $q$Facilitation playbook$q$, $q$guide$q$, $q$15 min read$q$, NULL, $q$m-forest$q$, $q$Run sessions people actually want to attend$q$, $q$["facilitation"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["The difference between a meeting people dread and a session people talk about is preparation you can copy. This is our copy.","Openers that work, timeboxes that hold, and the three sentences that rescue a room that’s gone quiet."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$show-your-work-portfolio-guide$q$, $q$Show your work: portfolio guide$q$, $q$guide$q$, $q$10 min read$q$, NULL, $q$m-navy$q$, $q$Turn cycle work into public, citable evidence$q$, $q$["writing"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["You did the work — now make it visible. This guide turns cycle work into portfolio evidence: what to show, what to say about it, and how to make claims someone can check.","You keep the craft, the credit, and the story. This is how you tell it."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$building-with-ai-recorded$q$, $q$Building with AI, recorded$q$, $q$recording$q$, $q$45 min watch$q$, NULL, $q$m-teal$q$, $q$A full session replay — build a small AI tool$q$, $q$["ai"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["The full replay of our most-requested session: one small AI tool, built live, start to finish — every wrong turn left in.","Watch it with a project in mind. Pause where we pause. Build alongside the recording and you’ll have something working by the end."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$project-starter-kit$q$, $q$Project starter kit$q$, $q$template$q$, $q$Reusable$q$, NULL, $q$m-forest$q$, $q$A ready-to-fork structure for a new project$q$, $q$["product"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$MIT code · CC BY 4.0 content$q$, $q$["A ready-to-fork project skeleton: the folder structure, the readme that answers the questions people actually ask, and the checklist from first commit to first user.","Copy it, adapt it, ship it. Starting from zero is a choice — stop making it."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$from-idea-to-shipped$q$, $q$From idea to shipped$q$, $q$course$q$, $q$5 lessons · self-paced$q$, NULL, $q$m-navy$q$, $q$A short course taking one idea all the way to shipped$q$, $q$["product"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["Five lessons, one idea — yours. Each lesson ends with your project one step closer to real: scoped, prototyped, tested, polished, shipped.","Go at your own pace, but go. The course only works if your idea rides along."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$run-your-own-build-night$q$, $q$Run your own build night$q$, $q$playbook$q$, $q$Playbook · open$q$, NULL, $q$m-forest$q$, $q$The replicable playbook for hosting a build night$q$, $q$["facilitation","civic"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["The same playbook we run, in every city: the room setup, the two-line agenda, the opener, and how to end so people come back.","A build night needs a host, a room, and this document. If your city is on a waitlist, this is how the waiting starts to feel like building."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$design-basics-for-builders$q$, $q$Design basics for builders$q$, $q$guide$q$, $q$8 min read$q$, NULL, $q$m-teal$q$, $q$The essentials to make your work look intentional$q$, $q$["design"]$q$::jsonb, $q$published$q$, NULL, $q$The Upskilling Labs$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["Six rules that make work look intentional: alignment, spacing, one typeface, real contrast, fewer colors, and let it breathe.","Eight minutes to read. The discipline to apply them is on you — but now you’ll see every violation, everywhere, forever. Sorry."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO resources (slug, title, content_type, meta, img, grad, summary, tags, status, from_line, author, url, license, body)
VALUES ($q$data-storytelling-recorded$q$, $q$Data storytelling, recorded$q$, $q$recording$q$, $q$60 min watch$q$, NULL, $q$m-navy$q$, $q$Turn data into a story people remember$q$, $q$["data","writing"]$q$::jsonb, $q$published$q$, NULL, $q$Marcus Bell · Data mentor$q$, $q$#$q$, $q$CC BY 4.0$q$, $q$["The full recording of the data storytelling session: three real charts rebuilt live — same numbers, completely different impact.","Watch it before your next readout. Your audience will notice the difference even if they can’t name it."]$q$::jsonb)
ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content_type=EXCLUDED.content_type, meta=EXCLUDED.meta, img=EXCLUDED.img, grad=EXCLUDED.grad, summary=EXCLUDED.summary, tags=EXCLUDED.tags, status=EXCLUDED.status, from_line=EXCLUDED.from_line, author=EXCLUDED.author, url=EXCLUDED.url, license=EXCLUDED.license, body=EXCLUDED.body, updated_at=NOW();

INSERT INTO metros (slug, name, st, status, partner, members, waiting_baseline, blurb)
VALUES ($q$dc$q$, $q$Washington, DC$q$, $q$DC$q$, $q$active$q$, $q$DC Public Library$q$, 312, 0, $q$The flagship. Weekly workshops, monthly showcase, a cycle in progress.$q$)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, st=EXCLUDED.st, status=EXCLUDED.status, partner=EXCLUDED.partner, members=EXCLUDED.members, waiting_baseline=EXCLUDED.waiting_baseline, blurb=EXCLUDED.blurb, updated_at=NOW();

INSERT INTO metros (slug, name, st, status, partner, members, waiting_baseline, blurb)
VALUES ($q$baltimore$q$, $q$Baltimore$q$, $q$MD$q$, $q$waitlist$q$, $q$Enoch Pratt Free Library$q$, NULL, 38, $q$Thirty-eight names and a library partner already at the table. Baltimore is close.$q$)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, st=EXCLUDED.st, status=EXCLUDED.status, partner=EXCLUDED.partner, members=EXCLUDED.members, waiting_baseline=EXCLUDED.waiting_baseline, blurb=EXCLUDED.blurb, updated_at=NOW();

INSERT INTO metros (slug, name, st, status, partner, members, waiting_baseline, blurb)
VALUES ($q$philadelphia$q$, $q$Philadelphia$q$, $q$PA$q$, $q$waitlist$q$, $q$Free Library of Philadelphia$q$, NULL, 57, $q$The longest list outside DC. Fifty-seven people are ready to build — Philadelphia is next in line by the numbers.$q$)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, st=EXCLUDED.st, status=EXCLUDED.status, partner=EXCLUDED.partner, members=EXCLUDED.members, waiting_baseline=EXCLUDED.waiting_baseline, blurb=EXCLUDED.blurb, updated_at=NOW();

INSERT INTO metros (slug, name, st, status, partner, members, waiting_baseline, blurb)
VALUES ($q$greensboro$q$, $q$Greensboro$q$, $q$NC$q$, $q$waitlist$q$, NULL, NULL, 12, $q$Twelve names in and growing. Greensboro’s list started the way every lab starts — with one person.$q$)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, st=EXCLUDED.st, status=EXCLUDED.status, partner=EXCLUDED.partner, members=EXCLUDED.members, waiting_baseline=EXCLUDED.waiting_baseline, blurb=EXCLUDED.blurb, updated_at=NOW();

INSERT INTO metros (slug, name, st, status, partner, members, waiting_baseline, blurb)
VALUES ($q$columbia$q$, $q$Columbia$q$, $q$SC$q$, $q$waitlist$q$, NULL, NULL, 9, $q$Nine people want a Columbia lab. A college town with a builder streak — the list knows it.$q$)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, st=EXCLUDED.st, status=EXCLUDED.status, partner=EXCLUDED.partner, members=EXCLUDED.members, waiting_baseline=EXCLUDED.waiting_baseline, blurb=EXCLUDED.blurb, updated_at=NOW();

INSERT INTO metros (slug, name, st, status, partner, members, waiting_baseline, blurb)
VALUES ($q$pittsburgh$q$, $q$Pittsburgh$q$, $q$PA$q$, $q$waitlist$q$, NULL, NULL, 26, $q$Steel built this city. The next thing gets built by the people who live here — 26 of them are already on the list.$q$)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, st=EXCLUDED.st, status=EXCLUDED.status, partner=EXCLUDED.partner, members=EXCLUDED.members, waiting_baseline=EXCLUDED.waiting_baseline, blurb=EXCLUDED.blurb, updated_at=NOW();

INSERT INTO metros (slug, name, st, status, partner, members, waiting_baseline, blurb)
VALUES ($q$miami$q$, $q$Miami$q$, $q$FL$q$, $q$waitlist$q$, NULL, NULL, 41, $q$Forty-one names deep and moving fast. Miami wants a lab, loudly.$q$)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, st=EXCLUDED.st, status=EXCLUDED.status, partner=EXCLUDED.partner, members=EXCLUDED.members, waiting_baseline=EXCLUDED.waiting_baseline, blurb=EXCLUDED.blurb, updated_at=NOW();

