-- 00089_backfill_civics_survey_responses.sql
-- Backfill the 31 responses collected on the original Civics & Elections Google
-- Form into the field-survey bedrock (survey_responses), attached to the seeded
-- 'civics' field_survey (00053). This is the pre-app evidence that the in-app
-- intake (00053/00061) replaced; importing it means the Triangulator export and
-- the participant aggregate see the full observation set, not just post-launch
-- submissions.
--
-- Mapping (Google Form column -> survey_responses):
--   Timestamp                       -> created_at (interpreted America/New_York)
--   Consent to Participation        -> consent_participation (all = true)
--   What are you observing...       -> observation
--   What is your experience...      -> standpoint[] (mapped to STANDPOINTS keys)
--   How much does this matter...    -> salience (1-5)
--   Has anyone tried to address...  -> prior_attempts
--   Can participants follow up...   -> contactable
--   Your Name                       -> submitter_name
--   Interested in mentoring...      -> mentor_interest ("Yes..." = true)
--   Email address                   -> submitter_email (lowercased)
--   Phone number                    -> submitter_phone
--
-- Notes:
--   * participant_id is NULL for every row: these are external form submissions,
--     not signed-in members (mirrors the anonymous intake path).
--   * moderation_status stays 'pending' (the default) -- backfilled rows enter
--     the same curation queue as live submissions; nothing is auto-approved.
--   * consent_version is stamped from the field_surveys row (as the API does),
--     not hardcoded here.
--   * One respondent typed a name into the email field ("Suzanne Wells"); that
--     non-email value is dropped (submitter_email NULL), the name is retained.
--   * All standpoint values in this dataset are single-select; stored as
--     one-element arrays (empty array when the optional field was blank).
--   * source_url is stamped with a provenance sentinel so every backfilled row
--     is self-identifying (audit + a clean, runnable DOWN). It's the documented
--     "evidence producer (uploaded-source origin)" column; no reader keys on it.
--
-- Idempotent: per-row guard on (field_survey_id, created_at). The form
-- timestamps are unique to the second, so a re-run inserts nothing.
--
-- DOWN:
--   DELETE FROM survey_responses
--   WHERE source_url = 'gform:civics-elections-2026';

WITH survey AS (
  SELECT id, consent_version FROM field_surveys WHERE share_slug = 'civics'
),
incoming (
  created_at, observation, standpoint, salience, prior_attempts,
  contactable, submitter_name, submitter_email, submitter_phone, mentor_interest
) AS (
  VALUES
    ('2026-06-09 18:21:11 America/New_York'::timestamptz, 'Just turn the USA into Switzerland politically '::text, ARRAY['other']::text[], 3::smallint, 'Nope '::text, true::boolean, 'AK'::text, NULL::text, '3016359754'::text, false::boolean),
    ('2026-06-09 18:21:29 America/New_York'::timestamptz, 'A', ARRAY[]::text[], 3, NULL, true, NULL, NULL, NULL, false),
    ('2026-06-09 18:22:19 America/New_York'::timestamptz, 'The misinformation of media and influencing ', ARRAY['other']::text[], 3, 'Not sure', false, NULL, NULL, NULL, false),
    ('2026-06-09 18:24:21 America/New_York'::timestamptz, 'Too much money in politics. At the congressional level, few districts are competitive. ', ARRAY['pay_attention']::text[], 5, NULL, false, NULL, NULL, NULL, false),
    ('2026-06-09 18:25:36 America/New_York'::timestamptz, 'Implementation of ranked choice voting in DC has lacked public education/awareness of the system’s benefits that are taken from experiences in other jurisdictions, as well as the body of political science literature about how it changes voting behaviors (eg, electoral engagement, strategic voting). ', ARRAY['research']::text[], 4, 'It isn’t clear to me what DC and stakeholder groups have done on this topic. However, this issue has been looked at in other jurisdictions (notably, NYC) that are similar to DC in terms of government structure. ', false, NULL, NULL, NULL, false),
    ('2026-06-09 18:27:29 America/New_York'::timestamptz, 'It''s too hard, expensive, and/or labor intensive to get clear insights on who is likely to be most effective in changing a legislator''s mind on a particular issue. There a million lists. There are a million issues. Who is most likely to be motivated to act who is ALSO the most likely person or groups of people to be effective on that particular issue, in that particular place, at that particular time, with that particular legislator. With the right inputs, this feels like a problem AI can help with. ', ARRAY['affected']::text[], 4, 'Unclear, big campaign tools (every action, salsa, etc.) probably have but not sure, and expensive!', true, 'Corey Ramsden', 'corey+upskilling@familysquish.com', NULL, false),
    ('2026-06-09 18:33:43 America/New_York'::timestamptz, 'I think that where I live in PG county a big issue is making enough actionable information about local county-level candidates easily available to voters. Many candidates don’t even submit official statements, and voters end up just voting for people whose faces they recognize from campaign signs. How can we not only get more information out to voters, but also incentivize candidates to engage more with voter questions and issues?', ARRAY['affected']::text[], 4, 'I recently discovered mypgvoterguide.com which does a good job of aggregating candidate information for voters, and it seems like a great tool. I just wish candidates would put more information out there about their goals and priorities.', true, 'Chelsea', 'chelsea.kirkland@dc.gov', NULL, false),
    ('2026-06-09 19:13:03 America/New_York'::timestamptz, 'AI is being implemented in all kinds of platforms and tools that impact our communities at a rate that often leaves people confused and concerned. What tools do communities have to feedback on and inform how AI tools are deployed by government agencies and/or companies in substantial ways, and how can they leverage them?', ARRAY['work_in_field']::text[], 3, 'Yes, many orgs but i don’t know of any current public facing opportunities for people to engage with this here in the DC area', true, 'Chelsea', 'chelsea.kirkland@dc.gov', NULL, false),
    ('2026-06-09 21:34:57 America/New_York'::timestamptz, 'Recyling bins in public spaces and in large buildings--like schools--get half-filled with trash, and that cross-contamination means the entire recycling contents have to be disposed of as trash (i.e. put in landfills). Seeing recycling bins full of trash is discouraging even to those who try to recycle, and becomes a self-perpetuating belief that recycling doesn''t work or matter, and is just another way that decays responsible civic behavior .', ARRAY['pay_attention']::text[], 5, 'Probably, but I haven''t seen wide-scale efforts myself.', true, 'Alex', NULL, NULL, false),
    ('2026-06-10 09:30:12 America/New_York'::timestamptz, 'Campaign finance', ARRAY['work_in_field']::text[], 5, 'Every reform effort runs into Citizens United', true, 'Jared Smith', 'jared@piper-smith.com', '8594949584', true),
    ('2026-06-10 09:58:10 America/New_York'::timestamptz, 'There is massive distrust in the act of voting, as well as the government, and the internet era of disinformation is worsening that an alarming rate. That combined with a lack of civics literacy has made for a terrible and toxic combination that, in my opinion, leads to firms leaning into the worst part of peoples current instincts in order to persuade voters.', ARRAY['work_in_field']::text[], 5, 'I have seen emerging tech that tries to combat disinformation once its identified, but it relies on catching it early, which relies on being in the right groups at the right time. I don''t know if we have figured out how to combat that at scale. ', true, 'Camille', 'camille@adwell.com', NULL, true),
    ('2026-06-10 09:58:33 America/New_York'::timestamptz, 'Too much talking, shaming, and not enough real/useful info. No one cares how people died to register/vote.  They do not see how their one vote makes a difference — both in outcome and in their own lives.  In many states it is a pain in the ass to vote — day care, taking off from work, getting to the polls, FILLING OUT THE STUPID BALLOT, confusing ballot, stupid poll workers, THE LIST GOES ON!!  1. Explain to people how voting controls their child’s school, their minimum wage jobs, how their garage is picked up. 2. Give out sample ballots and explain - in KY a voter only needs to vote for one person to have the ballot legal.  3. EDUCATED YOUR FRIGGING ELECTED OFFICIALS - most do not even know what a provisional ballot is or the laws in that state 4, PLAIN language for the laws and procedures 5. Have ways for people to get to the polls or vote, esp people who are alone and house bound 6. Yes, start on why and how to vote in the schools, yes even in preschool 7. Make sure ALL organizations like LWV who register people know WHAT THE FUCK THEY ARE DOING!! 8. Do not rely on news media or social media to educate people 9. Every frigging elected official needs an ONGOING course on elections and GOTV for their constituents (yes, i know most of them do not want people to vote) 10.STOP national groups like Vote411, etc from giving out advice/ help on voting — THEY GIVE OUT WRONG EVEN ILLEGAL information.  (Shall I go on????)', ARRAY['other']::text[], 4, 'DUH - because many elected officials do not want people to vote — how do you think they got into office?????   The groups that try, do it half heartedly and not consistently - plus no coordination.  The year i got about 40 nonprofits to work together WITH accurate information, Andy Beshear got elected by 5000 votes from Jefferson County. The year I chair the women’s vote project, more female judges were elected than ever before.  The Kids Vote Project, good idea but lost funding and volunteers.', true, 'Honi Marleen Goldman', 'honigoldman@gmail.com', '5024514564 (landline) 5024190426 (Text)', true),
    ('2026-06-10 12:16:59 America/New_York'::timestamptz, 'A fundamental component of democracy is compromise, that the common good demands universal acceptance of the need to  "get to ''Yes.'' " The failure of activists and the general electorate to recognize that principle has a major negative impact on civic engagement.', ARRAY['other']::text[], 4, 'See Judy Woodruff''s America at a Crossroads series, the Task Force for American Democracy.', true, 'Robert Becker', 'medialawyerdc@gmail.com', '202 306-2276', true),
    ('2026-06-10 14:12:30 America/New_York'::timestamptz, 'There is a real lack of talent pool/bench in jr roles. ', ARRAY['work_in_field']::text[], 5, 'Arena was a good program but I think it’s under funded now. ', true, 'Michelle Villegas Tapia', 'mav03372@gmail.com', '7735129750', true),
    ('2026-06-10 15:46:12 America/New_York'::timestamptz, 'There is a large disconnect between government officials and agencies (or schools) and the desires of their consituancies (school community).  When we talk about transparency, it often comes across as a false flag, which gives a sense of being ignored or dismissed.  It''s also not clear what the reasons for choices are, and how the rest of the community feels either.  I want a better way of communicating with our government, seeing what the sentiments of the community are in aggregate lifting up voices on all ends of the spectrum in more productive ways.   

I think about this in the context of our school''s PTA, and have been struck by what passes as listening by the school district. It''s hard for me to imagine how the district makes such large decisions with such little information from the community.', ARRAY['affected']::text[], 4, 'I''m sure that they have, just don''t know how.', true, 'Emily Modde', 'emodde@gmail.com', '415-963-2270', true),
    ('2026-06-10 20:58:15 America/New_York'::timestamptz, 'AI rendering actual constituent engagement ineffective because bots “flood the zone”', ARRAY['work_in_field']::text[], 4, 'No', false, NULL, NULL, NULL, false),
    ('2026-06-10 21:11:15 America/New_York'::timestamptz, 'Feeling not very hopeful. Also not so sure when next elections are for my area so tend to rely on word of mouth or flyers/mailers.', ARRAY[]::text[], 2, NULL, false, NULL, NULL, NULL, false),
    ('2026-06-10 22:37:55 America/New_York'::timestamptz, 'Elections - politicians choosing voters not the other way around; structural privileges enjoyed by the two dominant parties; growing size of voting districts.', ARRAY['pay_attention']::text[], 3, NULL, true, 'Prasanna Lal Das', 'prasannalaldas@yahoo.com', NULL, false),
    ('2026-06-11 09:05:26 America/New_York'::timestamptz, 'Issue 1: A key issue is the polarization of views, which occurs in part because people are able to live, work, and play with only people who have similar views (within their own bubble). This results in citizens proposing solutions or pushing back on reforms without seeing or considering the impacts of their positions on people beyond their social circle. This is not just a problem with those with conservative views. Liberals have also been known to support NIMBY positions. City/state officials often do not feel like they can push back against vocal voters. Could there be a tool used by either city offices or the NIMBY advocates themselves that forces some introspection (or for city officials, provides top cover and a counterpoint to vocal advocates) to consider these aspects of an issue/position: impact on others, distribution of burdens, equity and access, evidence vs. assumptions, long-term consequences, tradeoffs, and alternatives. Small city offices or officials like ANCs may not have the capacity to do this kind of analysis.  Issue 2: Parent volunteers, through PTAs/PTOs, can provide substantial support and benefits to schools; however, this work often falls on a few parents. Many of the PTA functions across schools in one school district are similar. Could a tool be developed that could reduce or simplify the workload on PTA leaders and provide continuity in knowledge and practices as PTA leaders turn over? Currently DCPS PTA leaders share knowledge via a What''s App online chat - including sharing best practices, answers on DCPS policies, sharing how problems were resolved, and explaining how to access a program or benefit for their PTA. Plenty of tools exist for repository and data sharing functions but I''m not sure there is one tool that consistently does it all. ', ARRAY['affected']::text[], 4, 'On issue 1, I assume some cities conduct equity assessments on policies, but the tool I am thinking of would be more accessible and has an educational introspection component. On issue 2, some PTAs have systems for retaining knowledge and sharing best practices, but it seems like there should be more ways to reduce PTA leader workload or enhance PTA operations (especially ones with very little capacity) by leveraging AI. Some lower SES schools have no PTA or the PTA may be 1-2 people - could an AI tool help these schools with either PTA-like functions or help manage parent engagement?', true, 'Grace Hu', 'ghgracehu@gmail.com', NULL, false),
    ('2026-06-11 09:31:08 America/New_York'::timestamptz, 'Many local civic (volunteer) organizations are led by and have as members older people. In my own neighborhood in southwest DC, I wonder what will happen to our local groups (Friends of Southwest Library, SWNA, Friends of Southwest, some local churches) when the leaders and members age out and there are no younger people to continue the groups. These groups often have limited capacity to recruit more people. Also, I suspect younger people have multiple competing priorities for their time, including managing their career or kids. ', ARRAY['affected']::text[], 3, 'I suspect this issue is facing local civics organization all over the country. I am not sure if anyone has tried to use AI/technology to help address it. You''d have to figure out which part of the problem to solve - helping civics orgs become attractive to younger people, helping civic orgs do outreach/recruit, helping civic orgs do succession planning?  ', true, 'Grace Hu', 'ghgracehu@gmail.com', NULL, false),
    ('2026-06-11 17:16:35 America/New_York'::timestamptz, 'Researching records of local elections candidates is challenging. Especially people that run uncontested. There is nothing out there on google that makes me feel ok about ticking a box. We need better ways to educate ourselves about the smaller decisions we’re voting on that don’t have communications budgets or a desire to share their voting or ruling records.', ARRAY['affected']::text[], 4, 'Not that I’ve seen', true, 'Rachael Wooden', 'rachael.wooden@gmail.com', '8053001365', true),
    ('2026-06-12 16:27:30 America/New_York'::timestamptz, 'I think that there''s a greater and growing sense of voter apathy because there''s an unfortunate sense of "my voice doesn''t count" across multiple communities. While that''s not entirely true, because if enough individuals go out and talk about a candidate and agree on issues and organize, a difference can be made, I also think that there''s a general feeling of pure stress and exhaustion that we are all feeling. That said, I think we need to make it less painful, and not commit to making others feel like they have to do a few extra steps and hurdles. The DC BOE did a great job at going out into communities and explaining what Rank Choice Voting is-there''s been a lot of wonderful resources and tutorials made available. They included thorough descriptions and directions on the ballot, but the one thing that they did not include that confused my colleagues who are first time District voters, was what each of the roles descriptions are for the races on the ballot. There needs to be a pamphlet with an organizational chart and breakdown of the roles within our local government, and there needs to be additional workshops explaining how those roles play an integral part into our democracy. ', ARRAY['pay_attention']::text[], 4, 'I have personally written and shared this feedback with my Councilmember who said that they would share this with their contacts in the BOE, but I have not seen a larger scale effort put in place to make this more tangible. ', true, 'Mary Ellen', 'maryellengolch@gmail.com', NULL, true),
    ('2026-06-15 13:41:24 America/New_York'::timestamptz, 'Design Thinking to Close the Partisan Gap 

Everyone agrees the problem is division, yet every attempt to fix it seems to deepen it. We talk endlessly about bipartisanship and listening to constituents—but the talking is the trap. Statements, town halls, and pledges are performances of collaboration rather than the thing itself. The gap that won''t close, no matter what people try, is the one between signaling an intent to work together and actually doing the work of it. What''s missing is a structured way for people who are supposed to disagree to sit in the same room and build something. THAT IS SOMETHING DESIGN THINKING IN A META SENSE CAN DO and what Upsikilling is already doing. The unglamorous work of empathy, define a shared problem, and prototype a solution before anyone plants a flag. Politics rewards the appearance of caring about a problem but not fixing one. I come at this from design thinking, where a sprint is a forcing function for exactly that kind of collaboration. I keep wondering why we treat it as a tool for product teams but never for the people whose entire job is solving shared problems - and I wonder are there any politicians in DC who would want to collaborate with Upskilling to dig in and solve the problems with us -- and perhaps even take this back with them to their home states. ', ARRAY['pay_attention']::text[], 4, 'I think there are various groups that are tackling crossing the divide. ', true, 'Heather', 'heather.ingram@gmail.com', '9148267312', true),
    ('2026-06-15 13:52:27 America/New_York'::timestamptz, 'We''re in the middle of what the former U.S. Surgeon General has named a loneliness epidemic—and underneath it is a civic problem we rarely name as one: the collapse of social scaffolding around how people form relationships and trust each other. A generation ago, that scaffolding came from places like churches, extended families, and shared cultural scripts. However restrictive those old rules were, they created real social accountability—consequences for how you treated people. That structure has largely dissolved, and nothing has replaced it.
What''s left is dating culture that''s become transactional and isolating, especially through apps. Women have gained agency and moved into spaces that were historically closed to them, which is a real gain—but there''s been no parallel conversation about what a healthy, accountable role looks like for men in this new landscape. The result is a vacuum: no shared rules, no norms, no clear expectations, and very little accountability for treating another person with respect. We see the symptoms everywhere—rising loneliness across men and women, declining birth and marriage rates, and a manosphere rushing to fill the gap with answers that mostly make things worse.
The piece that keeps being a problem no matter what people try is this: we keep diagnosing the symptom (loneliness, low birth rates, division between men and women) and almost never address the missing infrastructure—the absence of any shared, healthy framework for social accountability and relating. It feels like a private or cultural issue, but when isolation becomes a public health crisis and a driver of social fragmentation, it''s a civic one.', ARRAY['affected']::text[], 5, 'Vivek Murthy', true, 'Heather', 'heather.ingram@gmail.com', '9148267312', true),
    ('2026-06-15 14:23:45 America/New_York'::timestamptz, 'Small Organization Elections: When many people think of elections, they think of big, national or statewide governmental elections.  However, when I think of elections (particularly in the context of civics), I think of non-profit elections.  Union leadership elections, HOA elections, non-profit association Board elections.  These are organizations that often have more impact on your daily life than national leaders (they impact your paycheck, your working conditions, what you can build on your property), however they are often the elections that people are often the least tuned into, to the point that it is work to recruit anyone to fill these positions or get a quorum at meetings.

Many of these organizations rely on very outdated technology to conduct elections: within the last few years, I have voted for the leadership of some of the largest unions in the country by pencil and paper and by someone manning a gigantic excel spreadsheet and calling over 1,000 representative’s names one by one.    Sometimes this is driven by the fact that the leadership of these organizations is often retired (as many of these positions are volunteer).  Sometimes it is driven by intrenched interests and misaligned incentives (existing leaders have incentives to put up barriers to participation in elections to maintain power).  But often it is driven by the mismatch between what many voting systems are offering and what many small non-profit organizations need.  

Many systems are not geared towards transparent vote counting.  Systems like Survey Monkey are geared to provide data to the creator of the survey, and lack the transparency for voting members to be able to validate that the results are accurate.  These systems don’t have an incentive to create such metrics since they are selling themselves to the very leaders that are facing reelection and would benefit from being able to control the list of who receives a ballot.  This leads to members of these organizations refusing to support updates to the technology out of fear that it would compromise the integrity of the vote.

There are opportunities for using electronic voting methods to make leaders of these organizations more accountable to their members.  As a union president, I send out flash surveys regularly, and abide by the results, however more often these surveys go into a black box without results ever being reported back to membership.  I see an opportunity for a technological solution to this that would provide the necessary transparency and trust, while also making voting more efficient and perhaps increasing participation in these crucial civic organizations.
', ARRAY['work_in_field']::text[], 5, 'I feel like there are a lot of for-profit systems that cater to the needs of the existing leadership who have an incentive to make elections as difficult to participate in as possible.  It addresses the issue in theory, but in practice simply perpetuates the drivers of disinterest with these organizations.', true, 'Terry Fletcher', 'thaberdasher@gmail.com', NULL, true),
    ('2026-06-15 19:39:03 America/New_York'::timestamptz, 'No one can agree to disagree. Respect for others and their opinions is missing. ', ARRAY['affected']::text[], 4, 'All the time. Being an active listener and respecting others is very important. If you truly want to run and help for the right reasons. You will take everything into consideration. ', false, NULL, NULL, NULL, false),
    ('2026-06-21 22:23:42 America/New_York'::timestamptz, 'Combating misinformation has become a major part of the job. While there is outrage over various issues, there’s little understanding of who is responsible and what powers people in elected positions have to combat them independently. There’s even less understanding regarding understanding the complications of law in general which remains clouded due to the use of AI generated research which tends to remain vague and sometimes utterly false. 

Additionally, to know one’s fault, the speed at which people expect change is far outmatched but the realities at which they occur. Congress, whose creation specifically aimed to slow down the legal process works at half the speed people want it to. Which can at times be frustrating, but also protective. The debate that occurs on the floor, while seldom reflective of the debate happening online or amongst the public, has a reduced impact due to the speed at which debates and votes are had. The country is better off not being at the whims of every change and development even when we don’t see it. That lack of understanding regarding the importance of speed makes it all the more difficult for people to understand why things aren’t changing “fast enough.” 

Furthermore, the time issue does not stop at speed. While people travel thousands of miles to come meet with hill staff members and elected officials, the impact they may imagine they have is rather weakened by the staffs inability to manage so many issues. While every problem has importance, they cannot all be the MOST important and certainly aren’t treated that way. The constant meetings with different organizations, lobbyists, and advocates eats into the time staff members have to research, write, and read policy - further slowing down the congressional process. While the face time buys both party’s - congress and constituents - goodwill and compassion, it’s makes moving forward all the more difficult. This issue does not necessarily have a solution nor is a punishable problem, but it should be taken into consideration when analyzing the reasonability of constant engagement with a staff size of 50 meant to represent and respond to millions. 

To comment on the approach of elected officials, it seems that political parties spend too much time hoping people will learn to follow their lead and not enough time ensuring they are worth being followed. There is little forethought shown on a regular basis to indicate one’s ability to lead a nation to a brighter future. If the elected aren’t willing to lead and the leaders aren’t the ones elected, the nation will spend the rest of its dwindling life spiraling downwards. While times seem bleak, there must be a serious understanding that electing the right person has a profound impact on the individual''s ability to live a fruitful life. While people yearn to engage in the political process, the lacking ability of the majority parties to face the call of leadership makes electing people seem meaningless. The courage that some have to run against incumbents to overturn decades of the same type of leaderships is paramount to progress.', ARRAY['work_in_field']::text[], 5, 'There have been considerations for other formats of governance. To the credit of our current operational structure, a democracy to represent this amount of people has never been attempted. While it is not the largest congregation of representatives, the network is extensive and if people knew where and on what level there issues truly fell, they would probably see more success in addressing their concerns.', true, 'Celine Apenteng', 'celineapenteng@gmail.com', NULL, true),
    ('2026-06-23 20:56:12 America/New_York'::timestamptz, 'Misinformation - people get information and news from so many sources these days and it’s difficult for election officials to cut through the noise to get their citizens the truth.

Additionally, there’s a growing distrust that, even if you trust your elections run by your town, you don’t trust the elections run by another city / state especially if they are the majority opposite party of you.

How do we increase voter education and trust only locally, but with the larger election system?', ARRAY['other']::text[], 4, 'Inviting community members into observe your local processes has seemed to work very well. However, there is still the need to trust those in other places', true, 'Emily Benz', 'emily@civicroundtable.com', NULL, false),
    ('2026-07-01 20:26:34 America/New_York'::timestamptz, 'What does it take to be a good citizen? What daily/weekly/monthly steps can one take to build oneself into a model citizen who votes, stays informed, participates in government, etc. Why does it all feel so overwhelming to some? Because information is scattered all over the place! 
', ARRAY['pay_attention']::text[], 5, 'Unsure', true, 'Kirsten Mitchell', NULL, NULL, true),
    ('2026-07-02 10:22:03 America/New_York'::timestamptz, 'So many people are not engaged in local or national politics.  Many don''t know who the candidates are or what the candidates'' positions are on issues.  Sadly, many don''t even vote.', ARRAY['pay_attention']::text[], 3, 'I think many try to address this.  Civic organizations organize candidate forums, political groups try to get out the vote, etc.  I''m sure someone(s) have studied why people don''t vote.', true, 'Suzanne Wells', NULL, '7039091653', true),
    ('2026-07-10 09:57:03 America/New_York'::timestamptz, 'Lack of dialogue among people who hold differing views about some particular topic', ARRAY['work_in_field']::text[], 4, 'We are trying, by using new engagement software ("Go Vocal"), with some success.', true, 'Chuck Elkins', '3d01@anc.dc.gov', NULL, false)
)
INSERT INTO survey_responses (
  field_survey_id, participant_id, observation, standpoint, salience, prior_attempts,
  consent_participation, consent_version, contactable, submitter_name, submitter_email,
  submitter_phone, mentor_interest, moderation_status, source_url, created_at
)
SELECT
  s.id, NULL, i.observation, i.standpoint, i.salience, i.prior_attempts,
  true, s.consent_version, i.contactable, i.submitter_name, i.submitter_email,
  i.submitter_phone, i.mentor_interest, 'pending', 'gform:civics-elections-2026', i.created_at
FROM incoming i CROSS JOIN survey s
WHERE NOT EXISTS (
  SELECT 1 FROM survey_responses sr
  WHERE sr.field_survey_id = s.id AND sr.created_at = i.created_at
);
